### PR TITLE
Use absolute path for require

### LINKED ISSUE #2: Browserify incompatibility
I encounter errors related to this module when trying to user browserify:
```
03 02 2017 13:12:28.521:ERROR [framework.browserify]: bundle error
03 02 2017 13:12:28.521:ERROR [framework.browserify]: Error: Cannot find module './lib/cb2promise' 
```

This is due to the `require` call in `index.js`.
Can I submit a pull request prefixing the path with `__dirname`?

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2

### CODE REVIEW

**Comment by Kikobeats** [comment]
Please uncommit 1.0.3, I will release the version after the PR!

**Comment by Kikobeats** [comment]
Also tests looks broken for mocha issue, need to remove the final return

**Comment by ghost** [comment]
@Kikobeats is it better like this? :smile:

**Comment by Kikobeats** [comment]
Thanks!

**Pull request merged**
